openapi: 3.0.0
info:
  title: Validate Address API
  description: API for validating and standardizing shipping addresses
  version: 1.0.0

servers:
  - url: /api/v1

paths:
  /shipping/validate-address:
    post:
      summary: Validate shipping address
      description: Validates and standardizes a shipping address
      operationId: validateAddress
      tags:
        - Shipping
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - address
              properties:
                address:
                  type: object
                  required:
                    - street_address1
                    - city
                    - postal_code
                    - country
                  properties:
                    street_address1:
                      type: string
                    street_address2:
                      type: string
                    city:
                      type: string
                    state:
                      type: string
                    postal_code:
                      type: string
                    country:
                      type: string
                validation_level:
                  type: string
                  enum: [basic, standard, strict]
                  default: standard
                  description: Level of validation required
                standardize:
                  type: boolean
                  default: true
                  description: Whether to standardize the address

      responses:
        '200':
          description: Address validation completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  is_valid:
                    type: boolean
                  standardized_address:
                    type: object
                    properties:
                      street_address1:
                        type: string
                      street_address2:
                        type: string
                      city:
                        type: string
                      state:
                        type: string
                      postal_code:
                        type: string
                      country:
                        type: string
                      country_code:
                        type: string
                  suggestions:
                    type: array
                    items:
                      type: object
                      properties:
                        street_address1:
                          type: string
                        street_address2:
                          type: string
                        city:
                          type: string
                        state:
                          type: string
                        postal_code:
                          type: string
                        country:
                          type: string
                        confidence_score:
                          type: number
                          format: float
                  validation_details:
                    type: object
                    properties:
                      status:
                        type: string
                        enum: [verified, partial_match, not_found]
                      confidence_score:
                        type: number
                        format: float
                      corrections:
                        type: array
                        items:
                          type: object
                          properties:
                            field:
                              type: string
                            original:
                              type: string
                            corrected:
                              type: string
                      warnings:
                        type: array
                        items:
                          type: string
                      metadata:
                        type: object
                        properties:
                          timezone:
                            type: string
                          coordinates:
                            type: object
                            properties:
                              latitude:
                                type: number
                              longitude:
                                type: number

        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [error]
                  message:
                    type: string
                  validation_errors:
                    type: array
                    items:
                      type: object
                      properties:
                        field:
                          type: string
                        error:
                          type: string

        '422':
          description: Address validation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [error]
                  message:
                    type: string
                  error_details:
                    type: object
                    properties:
                      reason:
                        type: string
                      field:
                        type: string
                      suggestion:
                        type: string