openapi: 3.0.0
info:
  title: Generate Invoice API
  description: API for generating invoices
  version: 1.0.0

servers:
  - url: /api/v1

paths:
  /payments/invoices:
    post:
      summary: Generate an invoice
      description: Generates an invoice for an order or transaction
      operationId: generateInvoice
      tags:
        - Payments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - order_id
                - customer_id
                - items
                - billing_address
              properties:
                order_id:
                  type: string
                  description: Order identifier
                customer_id:
                  type: integer
                  description: Customer identifier
                items:
                  type: array
                  items:
                    type: object
                    required:
                      - description
                      - quantity
                      - unit_price
                    properties:
                      description:
                        type: string
                      quantity:
                        type: integer
                      unit_price:
                        type: number
                        format: decimal
                      tax_rate:
                        type: number
                        format: decimal
                billing_address:
                  type: object
                  required:
                    - street
                    - city
                    - country
                    - postal_code
                  properties:
                    street:
                      type: string
                    city:
                      type: string
                    state:
                      type: string
                    country:
                      type: string
                    postal_code:
                      type: string
                payment_terms:
                  type: object
                  properties:
                    due_days:
                      type: integer
                    early_payment_discount:
                      type: number
                      format: decimal

      responses:
        '201':
          description: Invoice generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoice_id:
                    type: string
                    description: Unique invoice identifier
                  invoice_number:
                    type: string
                    description: Human-readable invoice number
                  invoice_url:
                    type: string
                    format: uri
                    description: URL to download invoice
                  due_date:
                    type: string
                    format: date
                  total_amount:
                    type: number
                    format: decimal
                  status:
                    type: string
                    enum: [generated, sent, paid, overdue]
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [error]
                  message:
                    type: string
                  validation_errors:
                    type: array
                    items:
                      type: object
                      properties:
                        field:
                          type: string
                        error:
                          type: string
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [error]
                  message:
                    type: string