openapi: 3.0.0
info:
  title: Manage Addresses API
  description: API for managing customer shipping and billing addresses
  version: 1.0.0

servers:
  - url: /api/v1

paths:
  /customers/{customerId}/addresses:
    get:
      summary: List customer addresses
      description: Retrieves all addresses for a customer
      operationId: listAddresses
      tags:
        - Customers
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
        - name: type
          in: query
          schema:
            type: string
            enum: [shipping, billing, all]
            default: all
      
      responses:
        '200':
          description: Addresses retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  addresses:
                    type: array
                    items:
                      $ref: '#/components/schemas/Address'

    post:
      summary: Add new address
      description: Adds a new address for a customer
      operationId: addAddress
      tags:
        - Customers
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddressInput'

      responses:
        '201':
          description: Address added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  address_id:
                    type: string
                  status:
                    type: string
                    enum: [success]
                  message:
                    type: string

  /customers/{customerId}/addresses/{addressId}:
    put:
      summary: Update address
      description: Updates an existing address
      operationId: updateAddress
      tags:
        - Customers
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
        - name: addressId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddressInput'

      responses:
        '200':
          description: Address updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [success]
                  message:
                    type: string

    delete:
      summary: Delete address
      description: Deletes an existing address
      operationId: deleteAddress
      tags:
        - Customers
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
        - name: addressId
          in: path
          required: true
          schema:
            type: string

      responses:
        '200':
          description: Address deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [success]
                  message:
                    type: string

components:
  schemas:
    Address:
      type: object
      properties:
        address_id:
          type: string
        type:
          type: string
          enum: [shipping, billing]
        is_default:
          type: boolean
        street_address1:
          type: string
        street_address2:
          type: string
        city:
          type: string
        state:
          type: string
        postal_code:
          type: string
        country:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    AddressInput:
      type: object
      required:
        - type
        - street_address1
        - city
        - postal_code
        - country
      properties:
        type:
          type: string
          enum: [shipping, billing]
        street_address1:
          type: string
        street_address2:
          type: string
        city:
          type: string
        state:
          type: string
        postal_code:
          type: string
        country:
          type: string
        is_default:
          type: boolean
          default: false