openapi: 3.0.0
info:
  title: Create Cart API
  description: API for creating new shopping carts
  version: 1.0.0

servers:
  - url: /api/v1

paths:
  /orders/carts:
    post:
      summary: Create a new shopping cart
      description: Creates a new shopping cart for a customer session
      operationId: createCart
      tags:
        - Orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - customer_id
                - session_id
              properties:
                customer_id:
                  type: integer
                  description: ID of the customer
                session_id:
                  type: string
                  description: Current session identifier
                
      responses:
        '201':
          description: Cart created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  cart_id:
                    type: string
                    description: Unique identifier for the cart
                  status:
                    type: string
                    enum: [success]
                  message:
                    type: string
                    example: "Shopping cart created successfully"
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [error]
                  message:
                    type: string
        '409':
          description: Active cart already exists for session
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [error]
                  message:
                    type: string
                  existing_cart_id:
                    type: string