openapi: 3.0.0
info:
  title: Search Products API
  description: API for searching and filtering products
  version: 1.0.0

servers:
  - url: /api/v1

paths:
  /inventory/products/search:
    get:
      summary: Search for products
      description: Searches and filters products based on various criteria
      operationId: searchProducts
      tags:
        - Inventory
      parameters:
        - name: query
          in: query
          description: Search term
          schema:
            type: string
        - name: category_id
          in: query
          description: Filter by category
          schema:
            type: integer
        - name: min_price
          in: query
          description: Minimum price filter
          schema:
            type: number
            format: decimal
        - name: max_price
          in: query
          description: Maximum price filter
          schema:
            type: number
            format: decimal
        - name: in_stock_only
          in: query
          description: Filter to only in-stock items
          schema:
            type: boolean
        - name: sort_by
          in: query
          description: Field to sort by
          schema:
            type: string
            enum: [name, price, created_at]
        - name: sort_order
          in: query
          description: Sort direction
          schema:
            type: string
            enum: [asc, desc]
        - name: page
          in: query
          description: Page number
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: per_page
          in: query
          description: Items per page
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20

      responses:
        '200':
          description: Search results retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        description:
                          type: string
                        price:
                          type: number
                          format: decimal
                        category_id:
                          type: integer
                        in_stock:
                          type: boolean
                        stock_quantity:
                          type: integer
                  total_count:
                    type: integer
                    description: Total number of matching products
                  page_count:
                    type: integer
                    description: Total number of pages
                  current_page:
                    type: integer
                    description: Current page number
        '400':
          description: Invalid input parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [error]
                  message:
                    type: string