openapi: 3.0.0
info:
  title: Manage Returns API
  description: API for handling product returns and return shipping labels
  version: 1.0.0

servers:
  - url: /api/v1

paths:
  /shipping/returns:
    post:
      summary: Create return request
      description: Initiates a return request for ordered items
      operationId: createReturn
      tags:
        - Shipping
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - order_id
                - items
                - reason
                - condition
                - return_method
              properties:
                order_id:
                  type: string
                  description: Original order identifier
                items:
                  type: array
                  items:
                    type: object
                    required:
                      - item_id
                      - quantity
                      - reason
                      - condition
                    properties:
                      item_id:
                        type: string
                      quantity:
                        type: integer
                        minimum: 1
                      reason:
                        type: string
                        enum: [wrong_item, defective, not_as_described, no_longer_needed]
                      condition:
                        type: string
                        enum: [unused, opened, damaged]
                      notes:
                        type: string
                reason:
                  type: string
                  description: Overall return reason
                condition:
                  type: string
                  enum: [unused, opened, damaged]
                return_method:
                  type: string
                  enum: [carrier_pickup, drop_off]

      responses:
        '201':
          description: Return request created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  return_id:
                    type: string
                    description: Return authorization number
                  return_label:
                    type: string
                    format: uri
                    description: Return shipping label URL
                  refund_estimate:
                    type: number
                    format: decimal
                    description: Estimated refund amount
                  instructions:
                    type: string
                    description: Return instructions
                  expiration_date:
                    type: string
                    format: date
                    description: Return label expiration date

        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [error]
                  message:
                    type: string
                  validation_errors:
                    type: array
                    items:
                      type: object
                      properties:
                        field:
                          type: string
                        error:
                          type: string

        '404':
          description: Order not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [error]
                  message:
                    type: string

  /shipping/returns/{returnId}:
    get:
      summary: Get return details
      description: Retrieves details of a return request
      operationId: getReturn
      tags:
        - Shipping
      parameters:
        - name: returnId
          in: path
          required: true
          schema:
            type: string

      responses:
        '200':
          description: Return details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReturnDetails'

    put:
      summary: Update return request
      description: Updates the status or details of a return request
      operationId: updateReturn
      tags:
        - Shipping
      parameters:
        - name: returnId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [pending, approved, in_transit, received, completed, cancelled]
                tracking_number:
                  type: string
                notes:
                  type: string

      responses:
        '200':
          description: Return request updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReturnDetails'

components:
  schemas:
    ReturnDetails:
      type: object
      properties:
        return_id:
          type: string
        order_id:
          type: string
        status:
          type: string
          enum: [pending, approved, in_transit, received, completed, cancelled]
        items:
          type: array
          items:
            type: object
            properties:
              item_id:
                type: string
              quantity:
                type: integer
              reason:
                type: string
              condition:
                type: string
              refund_amount:
                type: number
                format: decimal
        tracking_number:
          type: string
        return_label:
          type: string
          format: uri
        refund_status:
          type: string
          enum: [pending, processed, completed]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time