openapi: 3.0.0
info:
  title: Track Order API
  description: API for tracking order status and details
  version: 1.0.0

servers:
  - url: /api/v1

paths:
  /orders/{orderId}/track:
    get:
      summary: Track order status
      description: Provides order status and tracking information
      operationId: trackOrder
      tags:
        - Orders
      parameters:
        - name: orderId
          in: path
          required: true
          description: Order identifier
          schema:
            type: string
        - name: customer_id
          in: query
          required: false
          description: Customer identifier for verification
          schema:
            type: integer

      responses:
        '200':
          description: Order tracking information retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [success]
                  order_status:
                    type: string
                    enum: [pending, processing, shipped, delivered, cancelled]
                  tracking_info:
                    type: object
                    properties:
                      carrier:
                        type: string
                      tracking_number:
                        type: string
                      estimated_delivery:
                        type: string
                        format: date
                      current_location:
                        type: string
                      status_history:
                        type: array
                        items:
                          type: object
                          properties:
                            status:
                              type: string
                            timestamp:
                              type: string
                              format: date-time
                            location:
                              type: string
                            description:
                              type: string
                  order_details:
                    type: object
                    properties:
                      items:
                        type: array
                        items:
                          type: object
                          properties:
                            product_id:
                              type: integer
                            quantity:
                              type: integer
                            price:
                              type: number
                      shipping_address:
                        type: object
                        properties:
                          street:
                            type: string
                          city:
                            type: string
                          state:
                            type: string
                          postal_code:
                            type: string
                          country:
                            type: string
                      payment_status:
                        type: string
                        enum: [pending, paid, failed, refunded]
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [error]
                  message:
                    type: string
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [error]
                  message:
                    type: string
        '403':
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [error]
                  message:
                    type: string